#!/usr/bin/env python3
"""Create a minimal forge problem pack."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*$")

CONFIG = {
    "generations": 1,
    "batch_size": 1,
    "max_cheap_calls": 1,
    "max_smart_calls": 0,
    "temperature": 0.8,
    "parents": 1,
    "archive_capacity": 5,
    "seed": 7,
    "workers": 1,
}

PROBLEM_TEMPLATE = '''"""Minimal forge problem pack generated by scaffold_problem_pack.py."""


class Problem:
    DESCRIPTION = "Improve a short text while keeping it non-empty."

    def seed(self):
        return ["seed idea"]

    def score(self, cand: str):
        cand = cand.strip()
        if not cand:
            return float("-inf"), False
        return float(len(cand)), True
'''


def _write_if_safe(path: Path, text: str) -> bool:
    if path.exists():
        return path.read_text(encoding="utf-8") == text
    path.write_text(text, encoding="utf-8")
    return True


def scaffold(name: str, root: Path) -> Path:
    if not NAME_RE.fullmatch(name) or "/" in name or "\\" in name:
        raise ValueError("name must be a single safe directory name")

    project = root / name
    project.mkdir(parents=True, exist_ok=True)

    config_text = json.dumps(CONFIG, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    problem_text = PROBLEM_TEMPLATE
    if not _write_if_safe(project / "config.json", config_text):
        raise FileExistsError(f"{project / 'config.json'} exists with different content")
    if not _write_if_safe(project / "problem.py", problem_text):
        raise FileExistsError(f"{project / 'problem.py'} exists with different content")
    return project


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Scaffold a minimal forge problem pack.")
    parser.add_argument("--name", required=True, help="single directory name for the problem pack")
    parser.add_argument("--root", default="projects", help="directory that will contain the pack")
    args = parser.parse_args(argv)

    try:
        project = scaffold(args.name, Path(args.root))
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    print(project)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
